server:
  port: 7001

eureka:
  instance:
    hostname: config.micro.service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.micro.service:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/jasonGit/spring-config-learning
          search-paths: config
          username: zhangbin.zj@gmail.com
          password: hanhan1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  security:
    enabled: false