server.port: 9099
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka.micro.service:1234/eureka/

spring:
  application:
    name: oauth
#  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/noah_oauth
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "NOAH_"
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
