server:
  port: 8761
eureka:
  instance:
    hostname: eureka.micro.service
    registerWithEureka: false
    fetchRegistry: false
  client:
    serviceUrl:
      defaultZone: http://eureka.micro.service:8761/eureka/